### ISSUE TITLE
error while make

### ISSUE THREAD

**Issue by freeappmm** [magi-project/wolf-m7m-cpuminer-V2#1]
Hi,
what i'm doing wrong?
i get this while running make:
make  all-recursive
make[1]: Entering directory `/root/minerd/wolf-m7m-cpuminer-V2-master'
Making all in compat
make[2]: Entering directory`/root/minerd/wolf-m7m-cpuminer-V2-master/compat'
Making all in jansson
make[3]: Entering directory `/root/minerd/wolf-m7m-cpuminer-V2-master/compat/jansson'
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT dump.o -MD -MP -MF .deps/dump.Tpo -c -o dump.o dump.c
mv -f .deps/dump.Tpo .deps/dump.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT hashtable.o -MD -MP -MF .deps/hashtable.Tpo -c -o hashtable.o hashtable.c
mv -f .deps/hashtable.Tpo .deps/hashtable.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT load.o -MD -MP -MF .deps/load.Tpo -c -o load.o load.c
mv -f .deps/load.Tpo .deps/load.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT strbuffer.o -MD -MP -MF .deps/strbuffer.Tpo -c -o strbuffer.o strbuffer.c
mv -f .deps/strbuffer.Tpo .deps/strbuffer.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT utf.o -MD -MP -MF .deps/utf.Tpo -c -o utf.o utf.c
mv -f .deps/utf.Tpo .deps/utf.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..     -g -O2 -MT value.o -MD -MP -MF .deps/value.Tpo -c -o value.o value.c
mv -f .deps/value.Tpo .deps/value.Po
rm -f libjansson.a
ar cru libjansson.a dump.o hashtable.o load.o strbuffer.o utf.o value.o 
ranlib libjansson.a
make[3]: Leaving directory`/root/minerd/wolf-m7m-cpuminer-V2-master/compat/jansson'
make[3]: Entering directory `/root/minerd/wolf-m7m-cpuminer-V2-master/compat'
make[3]: Für das Ziel »all-am« ist nichts zu tun.
make[3]: Leaving directory`/root/minerd/wolf-m7m-cpuminer-V2-master/compat'
make[2]: Leaving directory `/root/minerd/wolf-m7m-cpuminer-V2-master/compat'
Making all in m7
make[2]: Entering directory`/root/minerd/wolf-m7m-cpuminer-V2-master/m7'
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..    -Ofast -march=native -flto -g -O2 -MT libm7m_a-haval.o -MD -MP -MF .deps/libm7m_a-haval.Tpo -c -o libm7m_a-haval.o `test -f 'haval.c' || echo './'`haval.c
cc1: Fehler: ungültiges Optionsargument »-Ofast«
cc1: Fehler: nicht erkannte Kommandozeilenoption »-flto«
make[2]: **\* [libm7m_a-haval.o] Fehler 1
make[2]: Leaving directory `/root/minerd/wolf-m7m-cpuminer-V2-master/m7'
make[1]: *** [all-recursive] Fehler 1
make[1]: Leaving directory`/root/minerd/wolf-m7m-cpuminer-V2-master'
make: **\* [all] Fehler 2

kind regards,
Marcus

**Comment by freeappmm** [comment]
Hi,
sorry i forgot to write which system i use... :-(
I'm using it on centos 6.6 64Bit

kind regards,
Marcus

**Comment by freeappmm** [comment]
Hi,
no response since 22 days... :-(
But now i'm able to build it. :-)
but now when i start it, i get Segmentation Fault: 11 :-(

What should i do to solve this?

regards,
Marcus

**Comment by magi-project** [comment]
Sorry for delayed response. This might be an option: 

CFLAGS="-O3 -march=native" ./configure

**Comment by freeappmm** [comment]
Hi,
thx.

like i have written above, i have solved it by my own :)

But i have same problem on my imac. segmentation fault 11.. :(
OS: 10.10.5
any idea?

**Comment by freeappmm** [comment]
CFLAGS="-O3 -march=native" ./configure 
does not work on my imac...

**Comment by joelao95** [comment]
If you can post the output, I can take a look. Also you can use the precompiled miner (GUI version also available) as follows:

https://github.com/magi-project/m-cpuminer-qt/releases
https://github.com/magi-project/m-cpuminer-v2/releases

**Comment by freeappmm** [comment]
Hi,
m-minerd does the job.
Thx.
